language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
install:
  - npm install -g codecov
before_script:
  - npm prune
after_success:
  - codecov
  - npm install request
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
